.github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20230109.1 have added Android SDK Platform android-33-ext4. Something, possible the gradle version bundled with qt does not parse this correctly, and sets androidCompileSdkVersion in android-build/gradle.properties to "ext4" instead of expected "33". This commit is a quick fix to the problem, so the build will revert to android-33 wich was used before 20230109.1.
The documentation for the added package in the image version can be found here:
https://github.com/actions/runner-images/pull/6895
=> Fix failing android workflow by removing android-33-ext4 from build image

.github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20230313.1 have added Android SDK Platform android-33-ext5. Something, possible the gradle version bundled with qt does not parse this correctly, and sets androidCompileSdkVersion in android-build/gradle.properties to "ext5" instead of expected "33". This commit is a quick fix to the problem, so the build will revert to android-33 which was used before 20230109.1.
This fix was previously added for android-33-ext4 in image 20230109.1 #11.
The documentation for the added package in the image version can be found here:
https://github.com/actions/runner-images/pull/7278
Note: Currently 20230313.1 is in progress of being rolled out, making which builds that failes or not pseudo-random.
=> Github actions: Remove android-33-ext5 from build image

src/FlightDisplay/GuidedActionsController.qml
It looks to me like:
1. https://github.com/mavlink/qgroundcontrol/pull/5066 hid the "Continue Mission" action on the last mission item.
2. https://github.com/mavlink/qgroundcontrol/commit/82cceb1ae7 changed from `missionController.visualItems.count` to `_missionItemCount` in order to fix https://github.com/mavlink/qgroundcontrol/issues/6835. This also introduced a new bug, hiding the action for the second last mission item.
This PR removes the mission item index check completely here since we want the "Continue Mission" action to be available for the last mission item as well.
=> Stop hiding "Continue Mission" action for the two last mission items

.github/workflows/windows_release.yml
The release component does not support backslash in path, so the path is converted to unix style.
=> Fix windows path for release

QGCCommon.pri
Backport of these two PRs to resolve build issues:
https://github.com/mavlink/qgroundcontrol/pull/10132 
Fix issue:
`error: argument 2 of ‘__atomic_load’ must not be a pointer to a ‘volatile’ type`
https://github.com/mavlink/qgroundcontrol/pull/10729
Fix the issue with airmap.
=> [BACKPORT]QGCCommon: Disable AIRMAP & qmlglsink: Update to the latest version

.github/workflows/android_release.yml
This will force gradle to use sdsk 33 only
Related issue as #14, picked from upstream.
=> Remove android sdks newer than 33

.github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20231217.2.0 have added Android
SDK Platform android-34-ext10. Current build setup seem to not support
anything newer than 33, so remove all ext* and 34 versions.
=> Github actions: Remove android-34-ext10 from build image

src/JsonHelper.cc, src/JsonHelper.h, src/MissionManager/RallyPoint.FactMetaData.json, src/MissionManager/RallyPoint.cc, src/MissionManager/RallyPoint.h, src/MissionManager/RallyPointController.cc, src/MissionManager/RallyPointController.h, src/MissionManager/RallyPointManager.cc, src/MissionManager/RallyPointManager.h, src/PlanView/RallyPointItemEditor.qml
Needed for https://github.com/aviant-tech/PX4-Autopilot/pull/49
Rally points can now be always active (default/old behavior) or setup to
only be valid for either MR or FW flight.
Uses parameter 1 in the MAVLink message
(https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_RALLY_POINT) to
set type, 0=Always, 1=MR only, 2=FW only.
This adds a new version number for rally points in the JSON plan file
(2->102), but old files can be opened (RP defaults to old behavior), and
if all RPs are always active, the plan will be saved on the old format
(version 2) to enable better cross compatibility for different versions
of QGC.
Also tidy up UI a bit, to better be able to show RP data:
Old:
New:
=> Add support for rally point types

src/FlightDisplay/FlyViewMap.qml, src/MissionManager/RallyPoint.cc, src/MissionManager/RallyPoint.h, src/PlanView/RallyPointMapVisuals.qml, src/QmlControls/MissionItemIndexLabel.qml
- **Add missing internal type signal in rally point**
- **Mark FW rally point as "important"**
=> Clearly mark "FW only" rally points

.github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20240414 have added Android
SDK Platform android-34-ext11. Current build setup seem to not support
anything newer than 33, so remove all ext* and 34 versions.
=> Github actions: Remove android-34-ext11 from build image

.github/workflows/android_release.yml, .travis.yml, deploy/docker/Dockerfile-build-android, src/VideoReceiver/README.md, src/VideoReceiver/VideoReceiver.pri
From 1.18.5, since this version is no longer available from the download
site used.
For old version, all but the newest patch seems to be removed:
https://gstreamer.freedesktop.org/data/pkg/android/
=> build: upgrade gstreamer for android to 1.18.6

.github/workflows/android_release.yml, .github/workflows/linux_release.yml, .github/workflows/windows_release.yml
This is normally what we want, and we will manually update it to
"latest" when it is ready for production.
=> Github actions: releases built on tag push will be pre-release

.github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20240609 have added Android
SDK Platform android-34-ext12. Current build setup seem to not support
anything newer than 33, so remove all ext* and 34 versions.
=> Github actions: Remove android-34-ext12 from build image

src/FlightMap/MapItems/VehicleMapItem.qml, src/Vehicle/MultiVehicleManager.cc, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/ui/toolbar/MultiVehicleSelector.qml
- **Add name to vehicles based system id**
- **Use vehicle name instead of system id for multi vehicle indications**
=> Use drone name in QGC

.github/workflows/android_release.yml
Github workflow image ubuntu-20.04 version 20240624 have added Android
SDK Platform android-35. Current build setup seem to not support
anything newer than 33, so remove all ext* and 34/35 versions.
=> Github actions: Remove android-35 from build image

src/QGCApplication.cc
As we handle this in the multi-qgc setup, this is not needed
=> fix: remove warning about newer version

src/ui/toolbar/GPSIndicator.qml
Instead of displaying hdop in toolbar, we display gps lock type. If locktype is 3D Lock or DPOS, we color the text orange. If the the type is 3D Lock, we display `3D`, as it takes less space. If the lock type is RTK fix or RTK float, we display `RTK`, as it takes less space.
=> feat: display gps lock in toolbar

src/FlightDisplay/FlyViewWidgetLayer.qml, src/FlightDisplay/TelemetryValuesBar.qml, src/FlightMap/Widgets/VehicleWarningSideBar.qml
Currently, sidebar gets overlapped by telemetry bar on small/medium screens, see image below. By placing the sidebar on top of the valueArea of the telemetrybar we avoid this. The same happens for the winch widget, so this could be applied there as well, but when the batterywidget is introduced, the telemetry bar will take less horizontal space, so then this may be less of an issue.
New solution:
Old solution:
=> fix: place warning sidebar above telemetry toolbar

.github/workflows/linux_release.yml, README.md
This is to ensure that the decision to bump the production QGC version is manual and not automatic.
=> ci: bump latest tag manually from cli

src/QGCApplication.cc
Previously we removed the popup about newer qgc versions, but still looked for it. Now we just avoid looking for newer versions, which results in no popup
=> fix: dont look for newer qgc versions

src/Vehicle/Vehicle.cc
This will make the drone point tangentially to the circle during ORBIT. The current default is to face the center of the circle.
See [ORBIT_YAW_BEHAVIOUR](https://mavlink.io/en/messages/common.html#ORBIT_YAW_BEHAVIOUR).
Tested in sim on desktop.
=> feat: face tangent to circle during orbit

src/FlightDisplay/GuidedActionsController.qml, src/MissionManager/AviantMissionTools.cc, src/MissionManager/GeoFenceController.cc, src/MissionManager/GeoFenceController.h, src/MissionManager/MissionController.cc, src/MissionManager/PlanMasterController.cc, src/MissionManager/PlanMasterController.h, src/MissionManager/RallyPointController.cc, src/MissionManager/RallyPointController.h, src/PlanView/PlanToolBarIndicators.qml, src/PlanView/PlanView.qml, src/PlanView/RallyPointMapVisuals.qml, src/Vehicle/Vehicle.cc, src/Vehicle/Vehicle.h, src/ui/toolbar/MainStatusIndicator.qml, src/ui/toolbar/MainToolBar.qml
This PR adds multiple features to prevent us from flying with unexpected mission/rallypoint/geofence:
- Block arming when sync is in progress
- Block arming when mission is dirty
- Block arming if error happened during sync
- Display sync status of rally points and geofence
- Display sync status in both flyview and planview
- Remove popup asking to discard or overwrite current plan, change to always keep current plan
Also some minor fixes:
- Clear missionfilename when downloading new mission from kyte
- Clear missionfilename when clearing mission
=> Remove need for restart after mission upload

src/ADSB/ADSBVehicle.cc, src/ADSB/ADSBVehicle.h, src/ADSB/ADSBVehicleManager.cc, src/FlightDisplay/FlyViewMap.qml, src/FlightMap/MapItems/VehicleMapItem.qml
It was reported that the pilot often had to rehide hidden vehicles, as they would be removed when no signal was received for two minutes, and then they would reappear. This PR therefore increases the expiration time to four minutes, to reduce the chance of this happens. This makes the stale vehicles appear for a long time, so we therefore mark vehicles with signal older than one minute as "old", reducing the opacity of their icon to 30%.
=> Mark old adsb vehicles

src/MissionManager/AviantMissionTools.cc, src/MissionManager/AviantMissionTools.h, src/PlanView/PlanView.qml
Support for new validator features.
Note: Winch patterns "V2" and "V3" does not exists and will fail if used now, they are added so we do not need to upgrade QGC again if the are supported later. We might consider to query the server for valid types later, rather than hard code them.
=> Separate winch and takeoff types in Aviant mission tools
